[package]
name = "mozjs"
description = "Rust bindings to the Mozilla SpiderMonkey JavaScript engine."
repository = "https://github.com/servo/rust-mozjs"
version = "0.1.13"
authors = ["The Servo Project Developers"]
build = "build.rs"
license = "MPL-2.0"

[build-dependencies]
cmake = "0.1"

[lib]
doctest = false

[features]
debugmozjs = ['mozjs_sys/debugmozjs']
promises = ['mozjs_sys/promises']

[dependencies]
lazy_static = "1"
libc = "0.2"
log = "0.4"
num-traits = "0.1.32"
mozjs_sys = "0.50.1"
